services:
  talaqqi-ai-server:
    build: .
    container_name: talaqqi_ai_server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/root/.cache/huggingface
    volumes:
      - .:/app
      - hf_cache:/root/.cache/huggingface
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3500M

volumes:
  hf_cache:
